### ISSUE TITLE
Использование методов класса как callback

### ISSUE THREAD

**Issue by 0050006100760065006c0046** [simolex/test-cpp#2]
Нестатичные методы так использовать нельзя.
https://github.com/simolex/test-cpp/blob/50abba749a8595da4be8cab6ebfd135b1dcb1da2/DoorManager.cpp#L91

**Comment by simolex** [comment]
Изначально создал методы статическими, но из-за проблемы с использованием не статических переменных решил переписать.
Разобрался. Поправил
